---

# Source variable file of users
- include_vars: vars/cxl_users.yml

- name: Creating CXL Users
  user:
    name: "{{ item.key }}"
    state: "{{ item.value.status }}"
    comment: "{{ item.value.gecos }}"
    uid: "{{ item.value.uid }}"
    group: "{{ item.value.group }}"
    groups: "{{ item.value.groups }}"
    shell: "{{ item.value.shell }}"
    create_home: "yes"
    home: "/home/{{ item.key }}"
    password: "*K*"
  loop: "{{ lookup('dict', cxl_users )}}"


- name: Remove password aging
  command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 {{ item.key }}
  loop: "{{ lookup('dict', cxl_users )}}"

- name: Create "Commercial TriplePoint Account"
  user:
    name: tptadmin
    state: present
    comment: "Commercial TriplePoint Account"
    uid: 128854
    group: tptdev
    shell: /bin/bash
    createhome: yes
    home: /home/tptadmin
    password: "*K*"

- name: Remove password aging for "Commercial TriplePoint Account"
  command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 tptadmin

- name: Create HOSC02
  user:
      name: hosc02
      state: present
      comment: "Commercial Reliability Monitoring and Tools
      uid: 122782
      group: commit
      groups: tptprod,tpttest,tptdev,tptfunc
      shell: /bin/bash
      createhome: yes
      home: /home/hosc02
      password: "*K*"
- name: Remove password aging for "HOSC02"
  command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 hosc02
