---
- name: Create "HOSC02"
  user:
    name: hosc02
    state: present
    comment: "HOSC02"
    uid: 122782
    group: commit
    groups: tptprod,tpttest,tptdev,tptfunc
    shell: /bin/bash
    createhome: yes
    home: /home/hosc02
    password: "*K*"
- name: Remove password aging for "HOSC02"
    command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 hosc02

- name: Create "Commercial TriplePoint Account"
    user:
    name: tptadmin
    state: present
    comment: "Commercial TriplePoint Account"
    uid: 128854
    group: user66
        shell: /bin/bash
    createhome: yes
    home: /home/tptadmin
    password: "{{ 'copCXL' | password_hash('sha512') }}"

- name: Remove password aging for "Commercial TriplePoint Account"
    command: /usr/bin/chage -d -1 -E -1 -m -1 -M -1 -W -1 tptadmin
